import { IUserInfoResult } from '../../../interfaces/IUser';

export const user: IUserInfoResult = {
  id: 50099,
  name: 'Diego',
  last_name: ' Gauto',
  email: 'diegogauto01@gmail.com',
  password: '123456',
  phone_number: '541153137872',
  role: 'user',
  photo: '/images/profile/default_img.png',
  score: 52.5,
  stripe_id: 'cus_NrJVaTFsL4Bk7W',
  provider: 'web',
  created_at: '2023-05-08T05:41:31.000Z',
  past_user: 'no',
  subscription: 0,
  last_sign_in: '2024-09-03T12:28:23.000Z',
  country: 'Argentina',
  conekta_id: 'cus_2uZTYcoXrXsiiMM17',
  terms: 1,
  come_from: 'Recomendación (amigo/familia)',
  origin_state: null,
  offer_reference: 'Recomendación (amigo/familia)',
  user_id: 50099,
  final_date: 1723790000,
  level: 0,
  method: null,
  payment_method: null,
  plan_id: null,
  plan_name: null,
  start_date: 1723570000,
  type: null,
  admin_update_id: 49678,
  is_canceled: 0,
  payment_methods: [],
  user_courses: [],
  user_progress: [],
  user_history: [],
  user_certificates: [],
  roles: [],
};
